#!/bin/bash

#SBATCH -A b2013028
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 24:00:00
#SBATCH --mail-user=xuyue.yang@su.se
#SBATCH --mail-type=ALL

module load python
module load bioinfo-tools
module load bowtie2
module load trinity
module load rsem
module load samtools

cd /proj/b2013028/INBOX/private/trinityfilter/new

#/proj/b2013028/INBOX/private/trinityfilter/trinityrnaseq-2.2.0/util/filter_low_expr_transcripts.pl --matrix /proj/b2013028/INBOX/private/calmrsem/calm.TPM.not_cross_norm --transcripts /proj/b2013028/INBOX/private/denocalm/trinitycalm/trinity.calm.a1/calmtrinity.fasta --trinity_mode --highest_iso_only > calmhighet.fasta

#/sw/apps/bioinfo/trinity/2.1.0/milou/util/misc/fasta_filter_by_min_length.pl /proj/b2013028/INBOX/private/trinityfilter/calmhighet.fasta 500 > calmhighest500.fasta

# /proj/b2013028/nobackup/private/denopus/trinity.pus.a1/Trinity.fasta # pusila fasta
# --highest_iso_only 
# --min_pct_dom_iso 51

#/proj/b2013028/INBOX/private/trinityfilter/trinityrnaseq-2.2.0/util/filter_low_expr_transcripts.pl --matrix /proj/b2013028/INBOX/private/rsem/pusiso.TMM.EXPR.matrix --transcripts /proj/b2013028/nobackup/private/denopus/trinity.pus.a1/Trinity.fasta --trinity_mode --min_pct_dom_iso 51 > pusTMM51.fasta

#/sw/apps/bioinfo/trinity/2.1.0/milou/util/misc/fasta_filter_by_min_length.pl /proj/b2013028/INBOX/private/trinityfilter/pusTMM51.fasta 500 > pusTMM51500.fasta

#/proj/b2013028/INBOX/private/trinityfilter/trinityrnaseq-2.2.0/util/filter_low_expr_transcripts.pl --matrix /proj/b2013028/INBOX/private/calmrsem/calm.TPM.not_cross_norm --transcripts /proj/b2013028/INBOX/private/denocalm/trinitycalm/trinity.calm.a1/calmtrinity.fasta --trinity_mode --min_pct_dom_iso 51 > calm51.fasta
#/sw/apps/bioinfo/trinity/2.1.0/milou/util/misc/fasta_filter_by_min_length.pl /proj/b2013028/INBOX/private/trinityfilter/calm51.fasta 500 > calm51500.fasta


#pusiso.TPM.not_cross_norm, new, generated by isoform matrix (.isoforms.results)
#pus2.TPM.not_cross_norm old

#####filter for TPM level 

#/proj/b2013028/INBOX/private/trinityfilter/trinityrnaseq-2.2.0/util/filter_low_expr_transcripts.pl --matrix /proj/b2013028/INBOX/private/calmrsem/calm.TPM.not_cross_norm --transcripts /proj/b2013028/INBOX/private/trinityfilter/calm51500.fasta --trinity_mode --min_expr_any 0.2 > calm515000.2.fasta
#/proj/b2013028/INBOX/private/trinityfilter/trinityrnaseq-2.2.0/util/filter_low_expr_transcripts.pl --matrix /proj/b2013028/INBOX/private/calmrsem/calm.TPM.not_cross_norm --transcripts /proj/b2013028/INBOX/private/trinityfilter/calm51500.fasta --trinity_mode --min_expr_any 0.5 > calm515000.5.fasta

#/proj/b2013028/INBOX/private/trinityfilter/trinityrnaseq-2.2.0/util/filter_low_expr_transcripts.pl --matrix /proj/b2013028/INBOX/private/rsem/pusiso.TPM.not_cross_norm --transcripts /proj/b2013028/INBOX/private/trinityfilter/pusTMM51500.fasta --trinity_mode --min_expr_any 0.2 > pus515000.2.fasta
#/proj/b2013028/INBOX/private/trinityfilter/trinityrnaseq-2.2.0/util/filter_low_expr_transcripts.pl --matrix /proj/b2013028/INBOX/private/rsem/pusiso.TPM.not_cross_norm --transcripts /proj/b2013028/INBOX/private/trinityfilter/pusTMM51500.fasta --trinity_mode --min_expr_any 0.5 > pus515000.5.fasta

#####filter for length
/sw/apps/bioinfo/trinity/2.1.0/milou/util/misc/fasta_filter_by_min_length.pl /proj/b2013028/INBOX/private/trinityfilter/longestisocalm.fasta 400 > longestisocalm400.fasta
/sw/apps/bioinfo/trinity/2.1.0/milou/util/misc/fasta_filter_by_min_length.pl /proj/b2013028/INBOX/private/trinityfilter/longestisopus.fasta 400 > longestisopus400.fasta
